### ISSUE TITLE
where is the WeedCeption_v1 model? 

### ISSUE THREAD

**Issue by aertist** [jcrodriguez1989/weeddream#1]

**Comment by jcrodriguez1989** [comment]
Hi, the model weighs 184M, so I did not upload it.

**Comment by aertist** [comment]
> Hi, the model weighs 184M, so I did not upload it.

Can you upload it on google drive then share the link? If its okay with you. 😀

**Comment by jcrodriguez1989** [comment]
I definitely could.
May I know what do you want the model for? :)

**Comment by aertist** [comment]
[THIS](https://www.reddit.com/r/deepdream/comments/lesdwm/developing_an_after_effects_plugin_for_deep/?utm_source=share&utm_medium=web2x&context=3)

**Comment by jcrodriguez1989** [comment]
Awesome, here you have https://figshare.com/articles/online_resource/Weedception_v1_trained_model/13775635
Please, get me informed on how it goes your project :)

**Comment by aertist** [comment]
Hey, can you tell me how this model was trained? using caffe or TF or Pytorch? :)
Thanks for sharing

**Comment by jcrodriguez1989** [comment]
It was TF/Keras, that is exactly what we have on this repo, particularly this script https://github.com/jcrodriguez1989/weeddream/blob/main/Script/01_retrain_inception.py .

**Comment by aertist** [comment]
I read your blog on medium. It was awesome. Can you tell me how much time it took to train this model and what hardware was used to train it? Or you did it in Google Colab?

**Comment by jcrodriguez1989** [comment]
I don't remember how long it took, it was not that long.
About 2500 images to train, this is my hardware xD https://www.bhphotovideo.com/c/product/1385569-REG/asus_ux461un_ds74t_i7_8550u_1_8ghz_16gb_512ssd.html
I think it took about 2hs, it ran on CPU (not GPU).
